Repository ZHAW-Team-Toxic/PM4-Team-Toxic, pull requests merged in 2025-03, with the labels that each got.

#59 Created Start- and LevelSelectionScreen while using SuperAdapter
  README.md
  frontier/assets/skins/skin.atlas
  frontier/core/src/main/java/com/zhaw/frontier/screens/LevelSelectionScreen.java
  frontier/core/src/main/java/com/zhaw/frontier/screens/LoadingScreen.java
  frontier/core/src/main/java/com/zhaw/frontier/screens/StartScreen.java
  frontier/test/src/main/java/com/zhaw/tests/screens/StartScreenTest.java
Labels: enhancement

#81 Create SkinComposer Documentation.md
  SkinComposer Documentation.md
Labels: documentation

#74 setup cd pipeline with releases
  .github/release.yml
  .github/workflows/cd.yml
  frontier/lwjgl3/build.gradle
Labels: devops
